# Generated by Django 5.1 on 2024-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_cliente', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Forma_de_pago', models.CharField(max_length=20)),
                ('Productos', models.CharField(max_length=50)),
                ('Saldo', models.PositiveBigIntegerField()),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
