# Generated by Django 5.1 on 2024-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('ID_Sucursal', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Horario', models.CharField(max_length=100)),
                ('Encargado', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.PositiveBigIntegerField()),
            ],
        ),
    ]
